### ISSUE TITLE
Change displayed order of activities

### ISSUE THREAD

**Issue by maiphuongfw** [frappe/crm#119]
Suggestion: In the activity log, displaying the latest activities at the top will help users catch up quickly with a glance instead of having to scroll many times

**Comment by shariquerik** [comment]
@maiphuongfw When you land on the lead/deal page it automatically scrolls to the bottom
The reverse order of activities is because the email box is at the bottom similar to any chat app (E.g. WhatsApp)
The scrolling issue will be solved later when I will introduce more collapsed sections in the activity area (e.g. Last Week, Last Month etc)
