### ISSUE TITLE
Untranslated points (part 2)

### ISSUE THREAD

**Issue by weldonsantos** [frappe/crm#181]
Hi,

I did the tests and I can’t translate these words:

![image](https://github.com/frappe/crm/assets/72267543/656ee2e1-5fcc-4035-9cb8-54ee9bd85d5e)

![image](https://github.com/frappe/crm/assets/72267543/fc82eed2-013f-4186-9b79-70bb735ac6c4)

![image](https://github.com/frappe/crm/assets/72267543/f416ab61-c91f-4b0e-b772-10ae6988ff7f)

![image](https://github.com/frappe/crm/assets/72267543/44b60550-685c-41b3-8be9-3aec3b59d6b6)

![image](https://github.com/frappe/crm/assets/72267543/c53675ad-f842-4205-a231-856899c15100)

![image](https://github.com/frappe/crm/assets/72267543/d946480b-66e6-4d07-a959-55a89befa483)

![image](https://github.com/frappe/crm/assets/72267543/964bf1d7-5362-473f-89d7-f89be855cc07)

![image](https://github.com/frappe/crm/assets/72267543/88c43053-92ea-4c3c-a63b-38f9ff37ff12)

![image](https://github.com/frappe/crm/assets/72267543/50b4c507-7e30-4d94-9e25-0a743b82f1a3)

![image](https://github.com/frappe/crm/assets/72267543/078faaec-897f-4c41-bfbf-e9df640ac6cb)

![image](https://github.com/frappe/crm/assets/72267543/19344449-b68d-48c8-b7b6-048768d47e65)

![image](https://github.com/frappe/crm/assets/72267543/3a55582c-23b0-4a7d-921c-0de9a7f322c0)

![image](https://github.com/frappe/crm/assets/72267543/8ce82b20-3b3b-4ed0-a9e3-4bbbd3e1525b)

![image](https://github.com/frappe/crm/assets/72267543/d287aac5-610f-4797-9a28-f56e6d0ddbac)

It would be interesting to have the ability to translate the values of the inputs.

**Comment by shariquerik** [comment]
![image](https://github.com/frappe/crm/assets/30859809/e4ab7afd-5b87-4c71-85fd-096bbcf6258b)

Translation for 'New Task' doesn't exist. If you want test just add translation record like this and check again
<img width="1304" alt="image" src="https://github.com/frappe/crm/assets/30859809/315c3604-0113-4e4c-8533-499dae64d86a">

Similarly most of the above mentioned translation works just that it does not exist

I have raised one fix : https://github.com/frappe/crm/commit/c09b4f6ae616d995ac789b1bc0255b5cc22892da


> It would be interesting to have the ability to translate the values of the inputs.

No it doesn't make sense since input value is written by the end user it should not be translatable since user will write in his own language
