### ISSUE TITLE
Clarification on Branches: main, develop, and Missing version-15

### ISSUE THREAD

**Issue by edardev** [frappe/crm#475]
Hello Frappe CRM team,

I was reviewing the repository and noticed there are currently only two branches:

1. develop
2. main

Could you please clarify:

1. Which branch is considered production-ready? Is it main?
2. What is the role of the develop branch? Is it intended for ongoing development or pre-release testing?
3. I couldn't find a branch like version-15, which I typically see in other Frappe-related repositories. Is there a plan to add version-specific branches for stable releases?

Thank you for your time and clarification!

**Comment by liamdmcgarrigle** [comment]
Main is the production branch. 
Develop is where changes are made and tested.

There are package releases from the repo that you pull instead of the "production branch". you can add the version tag instead of the branch name.
That way you can roll back or use older versions easier
![Screenshot 2024-12-19 at 8 50 03 AM](https://github.com/user-attachments/assets/1b334d7d-f1c7-44fb-82f8-b0640e7c874d)

This is how most of the frappe apps are doing it now, even erpnext
